version: '3.7'
services:
  postgresql-server:
    image: postgres:16
    container_name: postgresql-server
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-zabbix}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-zabbix}
      POSTGRES_DB: ${POSTGRES_DB:-zabbix}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - zabbix-net
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    restart: unless-stopped
    depends_on:
      - postgresql-server
    environment:
      DB_SERVER_HOST: postgresql-server
      POSTGRES_USER: ${POSTGRES_USER:-zabbix}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-zabbix}
      POSTGRES_DB: ${POSTGRES_DB:-zabbix}
      ZBX_LISTENIP: "0.0.0.0"        # Escuta em todas as interfaces
    ports:
      - "10051:10051"
    volumes:
      - zabbix-server-data:/var/lib/zabbix
      - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
      - zabbix-export-data:/var/lib/zabbix/export
    networks:
      - zabbix-net

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    restart: unless-stopped
    depends_on:
      - postgresql-server
      - zabbix-server
    environment:
      DB_SERVER_HOST: postgresql-server
      POSTGRES_USER: ${POSTGRES_USER:-zabbix}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-zabbix}
      POSTGRES_DB: ${POSTGRES_DB:-zabbix}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: ${PHP_TZ:-America/Sao_Paulo}
    ports:
      - "${ZABBIX_FRONTEND_PORT:-8080}:8080"  # Interface Web acess√≠vel
    volumes:
      - zabbix-web-data:/usr/share/zabbix
    networks:
      - zabbix-net

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "zabbix-server"
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: '10051'
      ZBX_SERVER_ACTIVE: zabbix-server
      ZBX_LISTENIP: "0.0.0.0"        # Escuta em todas as interfaces
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
    privileged: true
    networks:
      - zabbix-net

volumes:
  postgresql-data:
  zabbix-server-data:
  zabbix-snmptraps-data:
  zabbix-export-data:
  zabbix-web-data:

networks:
  zabbix-net:
    driver: bridge
